---
title: "Time Series Analysis"
author: "Ramnath K (22BM6JP38), Vaibhav Goyal (22BM6JP54)"
date: "`r Sys.Date()`"
abstract: "This is abract for the project"
knit: (function(inputFile, encoding) {
      out_dir <- "Report";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})
output:
  word_document: default
---

---

# Data is fetched from the Data subfolder.
# Knitted Output of the notebook will be stored in the Report subfolder.
# Flextable library is used to generate tables for word

---

***

# Initial Setup

### Import Libraries:

1.  *astsa* - for Time Series Analysis
    i.
2.  *readxl* - for importing data from Excel file
```{r lib import}
library(astsa)
library(readxl)
```

### Import Data

```{r data import}
data <- read_xlsx("./Data/US_MRTS.xlsx", sheet = 'Sales')
colnames(data)[3] <- 'Sales'
```

```{r include=FALSE}
flextable::flextable(head(data, 10))
```

```{r pressure, echo=FALSE, fig.width=9, fig.height=6}
data.ts = ts(data['Sales'])
plot(data.ts, type="o", pch = 20) 
abline(v = 200, col = 'red', lty = 2)
abline(v = 250, col = 'red', lty = 2)
abline(v = 335, col = 'blue', lty = 2)
abline(v = 350, col = 'blue', lty = 2)
```

```{r outliers}
print(n= 100, data[c(200:250, 335:350),])
```

```{r}
lag1.plot(data.ts,1)
```
```{r}
acf(data.ts, xlim=c(1,20))
```

```{r}
pacf(data.ts, xlim=c(1,20))
```
